version: '1'

services:
       
## PostgreSQL
  postgresql:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      #- POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/data